name: 機能追加
description: 新しい機能を提案
title: 機能追加
labels: ["enhancement"]
assignees:
  - shimomo
body:
  - type: textarea
    id: enhancement
    attributes:
      label: 概要
      placeholder: 追加したい機能を簡単に記述
    validations:
      required: true
