name: 機能追加
description: 新しい機能を提案
body:
  - type: textarea
    id: enhancement
    attributes:
      label: Add a summary
      placeholder: ここに新しい機能の概要を入力
    validations:
      required: true
assignees:
  - shimomo
labels: ["enhancement"]
title: ここに新しい機能のタイトルを入力
type: Feature
