name: 不具合報告
description: 発生している不具合を報告
body:
  - type: textarea
    id: bug_summary
    attributes:
      label: 不具合の概要
      placeholder: ここに不具合の概要を入力してください
    validations:
      required: true
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: 再現手順
      placeholder: 不具合を再現するための手順を詳しく記入してください
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: 期待される動作
      placeholder: 正常な動作を説明してください
  - type: textarea
    id: actual_behavior
    attributes:
      label: 実際の動作
      placeholder: 実際に起きている問題を説明してください
assignees:
  - shimomo
labels: ["bug"]
title: ここに不具合のタイトルを入力
type: Bug
