name: publish

on:
  push:
    tags:
      - '*.*.*'

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine toml

      - name: Sync version in pyproject.toml with git tag
        run: python sync_version.py
        env:
          GITHUB_REF: ${{ github.ref }}

      - name: Build package
        run: python -m build

      - name: Publish package to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*

      - name: Generate release notes
        id: release_notes
        run: |
          CURRENT_TAG=${GITHUB_REF#refs/tags/}
          PREV_TAG=$(git tag --sort=-creatordate | grep -v "^$CURRENT_TAG$" | head -n 1)
          echo "DEBUG: CURRENT_TAG=$CURRENT_TAG, PREV_TAG=$PREV_TAG"

          if [ -z "$PREV_TAG" ]; then
            NOTES="First release."
          else
            NOTES=$(git log ${PREV_TAG}..${CURRENT_TAG} --pretty=format:"- %s (%an, %ad)" --date=short)
            if [ -z "$NOTES" ]; then
              NOTES="No changes since last release."
            fi
          fi

          echo "notes<<EOF" >> $GITHUB_OUTPUT
          echo "$NOTES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          tag_name: ${{ github.ref_name }}
          body: |
            Release version ${{ github.ref_name }}

            Changes since last release:
            ${{ steps.release_notes.outputs.notes }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
